### ISSUE TITLE
README

### ISSUE THREAD

**Issue by honorableCon** [bayevels/orange-sms-ruby#3]
Je te pick ton readme

Parceque j'ai fais la meme chose en python et javascript

;-)

**Comment by bayevels** [comment]
Je t'en prie Honorable

**Comment by bayevels** [comment]
je penses par contre que a cause de la version v3 de l'api de Orange la partie **Generate Access token** est obsoléte j'ai pushé une nouvelle version mais j'ai pas eu le temps de update le README

**Comment by honorableCon** [comment]
j'ai la flemme d'écrire une documentation :-)
